# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
version: 3
blocks:
  - alignment: left
    type: prompt
    # newline: true
    segments:
      - type: aws
        style: powerline
        powerline_symbol: ÓÇ∞
        foreground: "#ffffff"
        background: "#FFA400"
        template: " Óû≠ {{.Profile}}{{if .Region}}@{{.Region}}{{end}}"
      - type: git
        style: powerline
        powerline_symbol: ' '
        foreground: '#193549'
        background: '#ffeb3b'
        background_templates:
          - '{{ if or (.Working.Changed) (.Staging.Changed) }}#FFEB3B{{ end }}'
          - '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}'
          - '{{ if gt .Ahead 0 }}#B388FF{{ end }}'
          - '{{ if gt .Behind 0 }}#B388FB{{ end }}'
        template: '{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}'
        properties:
          fetch_status: true
          fetch_upstream_icon: true
          untracked_modes:
            '/Users/user/Projects/oh-my-posh/': 'no'
          source: cli
          mapped_branches:
            'feat/*': 'üöÄ '
            'bug/*': 'üêõ '
      - type: node
        style: powerline
        powerline_symbol: ÓÇ∞
        foreground: "#ffffff"
        background: "#6CA35E"
        template: " Óúò {{ .Full }} "
      - type: go
        style: powerline
        powerline_symbol: ÓÇ∞
        foreground: "#111111"
        background: "#8ED1F7"
        template: " Óòß {{ .Full }} "
      - type: python
        background: '#FFDE57'
        foreground: '#111111'
        powerline_symbol: "ÓÇ∞"
        properties:
          display_mode: environment
          fetch_virtual_env: true
        style: powerline
        template: ' \ue235 {{ if .Error }}{{ .Error }}{{ else }}{{ .Venv }}{{ end }} '
      - type: kotlin
        style: powerline
        powerline_symbol: ' '
        foreground: '#ffffff'
        background: '#906cff'
        template: ' <b>K</b> {{ .Full }} '
      - type: upgrade
        style: plain
        foreground: '#111111'
        background: '#FFD664'
        properties:
          cache_duration: 168h
      - type: status
        style: diamond
        foreground: "#ffffff"
        background: "#00897b"
        background_templates:
          - "{{ if .Error }}#e91e63{{ end }}"
        trailing_diamond: ÓÇ¥
        template: "<#193549>ÓÇ∞</> Óà∫ "
        properties:
          always_enabled: true
  - alignment: left
    newline: true
    segments:
      - type: path
        style: powerline
        powerline_symbol: "ÓÇ∞"
        foreground: '#ffffff'
        background: '#61AFEF'
        properties:
          style: folder
console_title_template: '{{ .Folder }}'
final_space: true